/* AUTO-GENERATED by scripts/generate-pages.mjs — do not edit by hand */
import manifest from './pages-manifest.json';

export type PageContent = {
  title: string;
  description: string;
  heading: string;
  lead: string;
  sections: { title: string; paragraphs: string[] }[];
};

const pages = manifest as Record<string, PageContent>;

export function getPageContent(slug: string): PageContent {
  const fallback: PageContent = {
    title: 'Dr. Janet Duffy | Las Vegas Real Estate',
    description: 'Las Vegas real estate guidance from Dr. Janet Duffy, REALTOR®.',
    heading: 'Las Vegas Real Estate',
    lead: 'Expert guidance for buyers, sellers, and investors across the Las Vegas valley.',
    sections: [],
  };
  return pages[slug] ?? fallback;
}
