import { siteConfig } from '@/config/site.config';

/** Global JSON-LD graphs with 2026 Schema.org v30.0 enhancements for GEO/AEO */
export const globalSchemaGraph = [
  {
    '@context': 'https://schema.org',
    '@type': 'RealEstateAgent',
    '@id': `${siteConfig.url}#agent`,
    name: siteConfig.name,
    alternateName: siteConfig.alternateName,
    description:
      'Las Vegas real estate expert with 35+ years experience and $127M+ in career sales. Nevada-licensed real estate agent serving buyers, sellers, and investors across Las Vegas, Summerlin, Henderson, and the surrounding valley.',
    telephone: siteConfig.phone,
    email: siteConfig.email,
    url: siteConfig.url,
    image: `${siteConfig.url}${siteConfig.ogImage}`,
    worksFor: { '@id': `${siteConfig.url}#business` },
    priceRange: '$$$',
    knowsAbout: [
      'Las Vegas Real Estate Market',
      'Luxury Home Sales',
      'Relocation Services',
      'Investment Property Analysis',
      '55+ Active Adult Communities',
      'First-Time Home Buyers',
      'Executive Relocation',
    ],
    specialty: [
      'Las Vegas Real Estate',
      'Summerlin Luxury',
      'Henderson Real Estate',
      '55+ Communities',
      'Investment Properties',
    ],
    areaServed: [
      {
        '@type': 'City',
        name: 'Las Vegas',
        containedIn: { '@type': 'State', name: 'Nevada' },
      },
      { '@type': 'City', name: 'Summerlin' },
      { '@type': 'City', name: 'Henderson' },
      { '@type': 'City', name: 'North Las Vegas' },
      { '@type': 'Neighborhood', name: 'Skye Canyon' },
      { '@type': 'Neighborhood', name: 'Inspirada' },
      { '@type': 'Neighborhood', name: 'The Lakes' },
    ],
    memberOf: [
      { '@type': 'Organization', name: 'Nevada Real Estate Division' },
      {
        '@type': 'Organization',
        name: siteConfig.brokerage,
        url: siteConfig.brokerageUrl,
      },
      { '@type': 'Organization', name: 'National Association of REALTORS' },
    ],
    hasCredential: [
      {
        '@type': 'EducationalOccupationalCredential',
        credentialCategory: 'Professional License',
        recognizedBy: { '@type': 'Organization', name: 'Nevada Real Estate Division' },
        credentialNumber: siteConfig.license,
      },
    ],
    knowsLanguage: ['en-US'],
    serviceType: [
      'Buyer Representation',
      'Seller Representation',
      'Relocation Services',
      'Investment Consulting',
      'Market Analysis',
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'LocalBusiness',
    '@id': `${siteConfig.url}#business`,
    name: siteConfig.legalName,
    parentOrganization: {
      '@type': 'Organization',
      name: siteConfig.brokerage,
      url: siteConfig.brokerageUrl,
    },
    alternateName: `${siteConfig.alternateName} - Las Vegas Real Estate Expert`,
    telephone: siteConfig.phone,
    email: siteConfig.email,
    url: siteConfig.url,
    image: `${siteConfig.url}${siteConfig.ogImage}`,
    logo: `${siteConfig.url}${siteConfig.ogImage}`,
    address: {
      '@type': 'PostalAddress',
      streetAddress: siteConfig.address.street,
      addressLocality: siteConfig.address.city,
      addressRegion: siteConfig.address.region,
      postalCode: siteConfig.address.postalCode,
      addressCountry: siteConfig.address.country,
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: '36.1485',
      longitude: '-115.3274',
    },
    openingHours: siteConfig.hours,
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: [
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday',
          'Sunday',
        ],
        opens: '08:00',
        closes: '20:00',
      },
    ],
    priceRange: '$$$',
    currenciesAccepted: 'USD',
    paymentAccepted: 'Cash, Check, Credit Card',
    areaServed: {
      '@type': 'GeoCircle',
      geoMidpoint: {
        '@type': 'GeoCoordinates',
        latitude: '36.1699',
        longitude: '-115.1398',
      },
      geoRadius: '50000',
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    '@id': `${siteConfig.url}#website`,
    name: `${siteConfig.name} - Las Vegas Real Estate Expert`,
    url: siteConfig.url,
    publisher: { '@id': `${siteConfig.url}#business` },
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${siteConfig.url}/properties?q={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  },
];
