/** URL paths for sitemap — ported from legacy SvelteKit sitemap.xml */
export type SitemapRoute = {
  path: string;
  priority: number;
  changeFrequency:
    | 'always'
    | 'hourly'
    | 'daily'
    | 'weekly'
    | 'monthly'
    | 'yearly'
    | 'never';
};

export const sitemapRoutes: SitemapRoute[] = [
  { path: '', priority: 1, changeFrequency: 'weekly' },
  { path: 'get-started', priority: 0.9, changeFrequency: 'weekly' },
  { path: 'properties', priority: 0.9, changeFrequency: 'daily' },
  { path: 'home-value', priority: 0.8, changeFrequency: 'monthly' },
  { path: 'rentals', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'blog', priority: 0.7, changeFrequency: 'weekly' },
  { path: 'about', priority: 0.6, changeFrequency: 'monthly' },
  { path: 'services', priority: 0.8, changeFrequency: 'monthly' },
  { path: 'neighborhoods', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'testimonials', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'market-insights', priority: 0.7, changeFrequency: 'weekly' },
  { path: 'contact', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'faq', priority: 0.6, changeFrequency: 'monthly' },
  { path: 'resources', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'first-time-buyers', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'relocation', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'investment-guide', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'buying-guide', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'selling-guide', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'mortgage-calculator', priority: 0.6, changeFrequency: 'monthly' },
  { path: 'resources/school-districts', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'resources/moving-checklist', priority: 0.6, changeFrequency: 'monthly' },
  { path: 'resources/home-staging', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'resources/market-reports', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'resources/rent-vs-buy', priority: 0.6, changeFrequency: 'monthly' },
  { path: 'resources/closing-costs-calculator', priority: 0.6, changeFrequency: 'monthly' },
  { path: 'resources/home-inspection-guide', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'resources/real-estate-glossary', priority: 0.6, changeFrequency: 'monthly' },
  { path: 'communities/summerlin', priority: 0.9, changeFrequency: 'weekly' },
  { path: 'communities/skye-canyon', priority: 0.9, changeFrequency: 'weekly' },
  { path: 'communities/centennial-hills', priority: 0.9, changeFrequency: 'weekly' },
  { path: 'communities/henderson', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'communities/green-valley', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'communities/north-las-vegas', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'communities/boulder-city', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'communities/seven-hills', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'communities/southern-highlands', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'communities/mountains-edge', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'communities/anthem', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/luxury-homes', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/condos', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/single-family', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/townhomes', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/new-construction', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/gated-communities', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/golf-communities', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/55-plus-communities', priority: 0.8, changeFrequency: 'weekly' },
  { path: 'property-types/foreclosures', priority: 0.7, changeFrequency: 'weekly' },
  { path: 'property-types/short-sales', priority: 0.7, changeFrequency: 'weekly' },
  { path: 'listings-embedded', priority: 0.8, changeFrequency: 'daily' },
  { path: 'listings-list', priority: 0.8, changeFrequency: 'daily' },
  { path: 'past-sales', priority: 0.7, changeFrequency: 'weekly' },
  { path: 'services/buyer-representation', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/senior-housing', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/military-relocation', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/seller-representation', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/pricing-strategy', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/distressed-properties', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/luxury-homes', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/resort-properties', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/eco-friendly-homes', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/international-property', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/residential-specialist', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/commercial-real-estate', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/commercial-investment', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/commercial-consulting', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/residential-appraisal', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/property-management', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/real-estate-investing', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/land-investment', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/smart-home-technology', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/digital-marketing', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/social-media-marketing', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/inside-sales', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/general-appraisal', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/inclusive-real-estate', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/negotiation-expertise', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/mortgage-guidance', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'services/real-estate-education', priority: 0.7, changeFrequency: 'monthly' },
  { path: 'privacy', priority: 0.3, changeFrequency: 'yearly' },
  { path: 'terms', priority: 0.3, changeFrequency: 'yearly' },
  { path: 'quotes', priority: 0.4, changeFrequency: 'monthly' },
  { path: 'sitemap', priority: 0.5, changeFrequency: 'monthly' },
];
