/**
 * Generates Next.js App Router pages from legacy SvelteKit +page.svelte files.
 * Run: node scripts/generate-pages.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const routesDir = path.join(root, 'legacy-sveltekit', 'src', 'routes');
const appDir = path.join(root, 'src', 'app');

const SKIP_TOP = new Set(['api', 'sitemap.xml', 'todos', 'v0', 'google[verification_code]']);
const CUSTOM_PAGES = new Set(['contact', 'sitemap']);

function decodeHtml(s) {
  return s
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'");
}

function extractMeta(content) {
  const title = decodeHtml(content.match(/<title>([^<]*)<\/title>/i)?.[1]?.trim() ?? '');
  const description =
    content.match(/name="description"\s+content="([^"]*)"/i)?.[1]?.trim() ??
    content.match(/name='description'\s+content='([^']*)'/i)?.[1]?.trim() ??
    '';
  const h1 =
    decodeHtml(content.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]?.replace(/<[^>]+>/g, '').trim() ?? '') ||
    title.split('|')[0].trim();
  return { title, description, heading: h1 };
}

function* findPages(dir, prefix = '') {
  if (!fs.existsSync(dir)) return;
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    if (ent.name.startsWith('[')) continue;
    const rel = prefix ? `${prefix}/${ent.name}` : ent.name;
    const full = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      if (SKIP_TOP.has(ent.name) && !prefix) continue;
      yield* findPages(full, rel);
    } else if (ent.name === '+page.svelte') {
      yield prefix.replace(/\\/g, '/');
    }
  }
}

const manifest = {};

for (const slug of findPages(routesDir)) {
  if (!slug || CUSTOM_PAGES.has(slug)) continue;
  const file = path.join(routesDir, ...slug.split('/'), '+page.svelte');
  const content = fs.readFileSync(file, 'utf8');
  const meta = extractMeta(content);
  manifest[slug] = {
    ...meta,
    lead: meta.description,
    sections: meta.description
      ? [{ title: 'Overview', paragraphs: [meta.description] }]
      : [],
  };

  if (slug === '') continue;

  const segments = slug.split('/');
  const pageDir = path.join(appDir, ...segments);
  fs.mkdirSync(pageDir, { recursive: true });

  const pageTsx = `import { MigratedPage } from '@/components/pages/MigratedPage';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: ${JSON.stringify(meta.title || 'Dr. Janet Duffy | Las Vegas Real Estate')},
  description: ${JSON.stringify(meta.description)},
  alternates: {
    canonical: 'https://www.drjanetduffy.com/${slug}',
  },
};

export default function Page() {
  return <MigratedPage slug=${JSON.stringify(slug)} />;
}
`;
  fs.writeFileSync(path.join(pageDir, 'page.tsx'), pageTsx);
}

fs.writeFileSync(
  path.join(root, 'src', 'lib', 'pages-manifest.json'),
  JSON.stringify(manifest, null, 2),
);

const tsContent = `/* AUTO-GENERATED by scripts/generate-pages.mjs — do not edit by hand */
import manifest from './pages-manifest.json';

export type PageContent = {
  title: string;
  description: string;
  heading: string;
  lead: string;
  sections: { title: string; paragraphs: string[] }[];
};

const pages = manifest as Record<string, PageContent>;

export function getPageContent(slug: string): PageContent {
  const fallback: PageContent = {
    title: 'Dr. Janet Duffy | Las Vegas Real Estate',
    description: 'Las Vegas real estate guidance from Dr. Janet Duffy, REALTOR®.',
    heading: 'Las Vegas Real Estate',
    lead: 'Expert guidance for buyers, sellers, and investors across the Las Vegas valley.',
    sections: [],
  };
  return pages[slug] ?? fallback;
}
`;

fs.writeFileSync(path.join(root, 'src', 'lib', 'page-content.ts'), tsContent);

console.log(`Generated ${Object.keys(manifest).length} pages`);
